apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-main
  namespace: ads
  labels:
    app: ads-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ads-main
  template:
    metadata:
      labels:
        app: ads-main
        aadpodidbinding: ads-identity
    spec:
      containers:
      - name: ads-main
        image: chunliu.azurecr.io/ads-server:0.2.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: ASPNETCORE_HTTPS_PORT
            value: "443"
          - name: MIClientId
            value: "<managed identity>"
